spring:
  datasource:
    url: jdbc:mysql://test4.suiyi:3306/world
    username: root
    password: Windows2000!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true