spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://test4.suiyi:3306/world?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Windows2000!
    minIdle: 50
    validationQuery: SELECT 'x'
    initialSize: 50
    maxWait: 60000
    filters: stat,wall,slf4j
    logSlowSql: true
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    maxActive: 100
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
